-- 코드를 작성해주세요
/*
부모의 형질을 모두 보유한 대장균
ID(ID), 대장균의 형질(GENOTYPE), 부모 대장균의 형질(PARENT_GENOTYPE)을 출력
ID에 대해 오름차순 정렬
*/
# SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
SELECT B.ID, B.GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A
LEFT JOIN ECOLI_DATA B
ON A.ID = B.PARENT_ID
WHERE (A.GENOTYPE & B.GENOTYPE) = A.GENOTYPE
# ORDER BY ID ASC;