SELECT 
    b.TITLE,
    b.BOARD_ID,
    r.REPLY_ID,
    r.WRITER_ID,
    r.CONTENTS,
    TO_CHAR(r.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM 
    USED_GOODS_BOARD b
JOIN 
    USED_GOODS_REPLY r
ON 
    b.BOARD_ID = r.BOARD_ID
WHERE 
    EXTRACT(YEAR FROM b.CREATED_DATE) = 2022
    AND EXTRACT(MONTH FROM b.CREATED_DATE) = 10
ORDER BY
    r.CREATED_DATE ASC,
    b.TITLE ASC;